### ISSUE TITLE
Consulta retorna apenas o último objeto

### ISSUE THREAD

**Issue by Bavaresco** [osians/rastreamento-de-pedidos#1]
Recentemente a consulta parou de mostrar todos os dados internos, data, hora, status da movimentação. Atualizei o código implementando os últimos códigos que vc inseriu no teu script e agora só mostra o último status do rastreamento e exclui todo o histórico anterior...sabe como contornar isso?

**Comment by osians** [comment]
Olá Bavaresco, o código e consulta através de SOAP continuam funcionando perfeitamente.  Por volta do dia 20/06/2017 o Correios do Brasil passou a limitar os usuários que não utilizam credenciais ou que utilizam as credenciais ECT/SRO para realizar consultas. Sendo assim, para quem não tem usuário e senha dos correios, apenas o último evento é retornado. Eu não sei se isso será permanente ou temporário. Mas, caso você tenha usuário e senha dos correios, utilize para contornar esse problema.

**Comment by Bavaresco** [comment]
Opa. E como cria um usuário/senha dos correios? Há algum sistema de cadastro pra isto?

**Comment by osians** [comment]
Então, o correios tem o idCorreios que é um cadastro de usuário e senha que deveria servir para isso, mas infelizmente não serve! E não existe nada documentado ou claro em relação a isso. 
A alternativa definitiva é entrar em contato com os correios, através dos telefones ou da página de contato.
**Telefones:**
3003 0100 (Capitais e Região Metropolitanas)
0800 725 7282 (Demais localidades)
0800 725 0100 (Sugestões ou reclamações)
0800 725 0898 (exclusivo para portadores de deficiência auditiva)
3003 1383 (Informações Banco Postal)

**Página de contatos:**
http://www2.correios.com.br/sistemas/falecomoscorreios/ 

Recomendo os telefones pois o "falecomoscorreios" pode demorar muito.

**Comment by Bavaresco** [comment]
Vou entrar em contato e compartilho aqui o que der certo, se der...

**Comment by osians** [comment]
Perfeito, essa informação vai ser bastante útil para muitas pessoas que estão enfrentando o problema. 
Ha! Só um PS, não sei para qual finalidade você esta rastreando pedidos, e qual o nível de flexibilidade de informações que você precisa. Mas, qualquer coisa, há uma forma de fazer rastreamento simples através de CURL renderizando a página dos correios. Deixei um exemplo hoje em: http://sooho.com.br/2017/06/23/rastreamento-de-pedido-correios-por-renderizacao/ mas como falei não é tão flexível, mas dependendo do uso pode ser útil.

**Comment by thiagomotta** [comment]
Pessoal, alguém conseguiu alguma coisa? No 0800 ninguém sabe de nada

**Comment by thiagomotta** [comment]
Consegui efetuar um cadastro nesse idCorreios, mas por enquanto parece que não funciona

**Comment by osians** [comment]
Thiago, o idCorreios não serve mesmo.  Rastreamento sem usuário e senha agora só através de Renderização. Do contrário, precisa ir até a agência mais próxima. Mesmo ligando não tenho certeza se eles fazem esse tipo de cadastro.

**Comment by thiagomotta** [comment]
O ruim é que através de renderização não conseguimos pegar todos os dados, como TIPO e STATUS, além de que um tempo atrás eles também retornavam latitude e longitude

**Comment by osians** [comment]
Sim verdade! Mas tem como obter essas informações com um pouco de programação. Pois os status não mudam muito. **Objeto saiu para entrega ao destinatário** sempre será Tipo **OEC** e Status 0, assim como, **Objeto encaminhado**  sempre tem um padrão de Origem / Destino que é referente a alguma **Unidade Operacional dos Correios**. 
O Endereço completo dessas UOPs estão no serviço de DNE dos correios (mas é pago). Talvez o Google Maps possibilite obter Latitude, Longitude dessas UOPs e até traçar o caminho que o objeto vai percorrer.
O único problema em relação a qualquer coisa ligada a usar o serviço dos correios é que, eles mudam os webservices e documentação o tempo todo, e não informam nada acerca dessas alterações a quem utiliza os serviços. Então, para quem programa precisa estar ajustando tudo frequentemente.

**Comment by thiagomotta** [comment]
Esses correios sinceramente, lixo total!

**Comment by CaioSchmtt** [comment]
alguem descobriu alguma coisa? estou enfrentando o mesmo problema ...

**Comment by osians** [comment]
@CaioSchmtt a conclusão é que o Correios limitou a pesquisa via API. Caso você queira fazer uso da API precisa entrar em contato com Correios da sua cidade ou pelo 0800 e solicitar usuário e senha.  
Agora, se você apenas precisa rastreamentos simples, pode usar o rastreamento através de Renderização que, foi citado acima.

**Comment by thiagomotta** [comment]
o aplicativo Rastreador de Pacotes irá liberar a API para acesso externo.
Assim poderá usar a api para consultas, pode ser uma solução para você
@CaioSchmtt <https://github.com/caioschmtt>



*Att,*
*Thiago Motta Zappaterra*

*rastreadordepacotes.com.br <http://rastreadordepacotes.com.br>*
*grandescolecoes.com.br <http://grandescolecoes.com.br>*




Em 24 de agosto de 2017 15:41, Wanderlei Santana <notifications@github.com>
escreveu:

**Comment by Bavaresco** [comment]
@thiagomotta o app rastreador de pacotes é seu? e esta API faz o que exatamente? Como posso aplica-la a este sistema de rastreio de correios? Pois aqui já liguei em todos os 0800, faleconosco e correios presencialmente e ngm soube me passar um login/senha, apenas aquele idCorreios que não serve na verdade pra nada..

**Comment by thiagomotta** [comment]
@Bavaresco tudo bem? Sim, o aplicativo é meu! O idCorreios não serve pra nada! Pode me chamar via email que conversamos sobre o acesso externo: contato@rastreadordepacotes.com.br 

Abraço ;)
