### ISSUE TITLE
Mostrar todos os status

### ISSUE THREAD

**Issue by web1989** [osians/rastreamento-de-pedidos#3]
boa tarde
é possivel mostrar todos os status? atualmente só mostra postado.

**Comment by web1989** [comment]
Ele só mostra um evento 

NUMERO: XXXXXXXX
SIGLA: OJ
NOME: ETIQUETA LOGICA SEDEX OJ
CATEGORIA: SEDEX
TIPO: PO
STATUS: 01
DATA: 23/09/2020
HORA: 09:21
DESCRICAO: Objeto postado
LOCAL: AGF PENHA
CODIGO: 13970971
CIDADE: ITAPIRA
UF: SP

**Comment by osians** [comment]
Olá tudo bem?

primeiramente, gostaria de me desculpar pela resposta tão tardia a sua
mensagem. Mil desculpas.

Bom, quanto a sua dúvida, já faz 1 ou 2 anos que os Correios passaram a não
exibir, via API, todas as informações de rastreamento
de um objeto. Apenas o último evento do objeto é exibido utilizando as
credenciais de usuário e senhas default.
Essa função está disponível apenas para as pessoas ou empresas que tem
contrato com o correio., é necessário um usuário e senha
seus para que você tenha acesso a todas as informações através da API. Para
isso, você teria que se informar com os correios para adquirir essas
credenciais.

Existe uma outra maneira de obter todos os eventos dos correios, não é
através de uma API, mas sim através da página renderizada.
Bom, como isso funciona... .
os correios tem uma página onde você pode inserir um número de objeto, e
ele mostra todos os eventos do mesmo...
É possível através do PHP enviar um número de rastreamento para essa
página, e receber como resposta a página inteira...
Em seguida, o código precisa remover as informações desnecessária e obter
as informações apenas do rastreamento do produto.

esse método não é ideal, uma vez que caso os correios alterem essa página,
o seu codigo vai quebrar, e também, as informações obtidas são poucas se
comparado
àquelas obtidas através da API.

Bom, espero que isso lhe auxilie de alguma forma, novamente, me desculpe a
demora em respondè-lo e caso tenha alguma dúvida,
fique a vontade em perguntar.


Wanderlei Santana
